branch-defaults:
  default:
    environment: water-watch-project-dev
    group_suffix: null
global:
  application_name: water_watch_project
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
