# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usgs_site_code', models.CharField(max_length=20)),
                ('station_name', models.CharField(max_length=255, unique=True)),
                ('us_state_cd', models.CharField(max_length=2)),
                ('longitutde', models.DecimalField(decimal_places=3, max_digits=7)),
                ('latitutde', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
            options={
                'ordering': ['station_name'],
                'db_table': 'station',
            },
        ),
    ]
