# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_watch_api', '0002_auto_20180304_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('MAINTENANCE', 'maintenance')], default='ACTIVE', max_length=15)),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['sensor_type_name'],
                'db_table': 'sensor_type',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_watch_api.SensorType'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_watch_api.Station'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set([('station', 'sensor_type')]),
        ),
    ]
