# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_watch_api', '0003_auto_20180305_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_data_dateTime', models.DateTimeField()),
                ('sensor_data_value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_watch_api.Sensor')),
            ],
            options={
                'ordering': ['sensor_data_dateTime'],
                'db_table': 'sensor_data',
            },
        ),
        migrations.RenameField(
            model_name='station',
            old_name='latitute',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
