# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_watch_api', '0004_auto_20180307_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['id', 'sensor_data_dateTime'], 'verbose_name_plural': 'sensor data'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['id', 'station_name']},
        ),
    ]
