# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_watch_api', '0006_auto_20180329_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensordata',
            unique_together=set([('sensor', 'sensor_data_dateTime')]),
        ),
    ]
