# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_watch_api', '0007_auto_20180404_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorMaintenanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('MAINTENANCE', 'maintenance')], default='ACTIVE', max_length=15)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_watch_api.Sensor')),
            ],
            options={
                'db_table': 'sensor_maintenance_history',
                'verbose_name_plural': 'sensor maintenance history',
                'ordering': ['id', 'dateTime'],
            },
        ),
        migrations.AddField(
            model_name='station',
            name='current_status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('MAINTENANCE', 'maintenance')], default='ACTIVE', max_length=15),
        ),
    ]
