# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 22:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_watch_api', '0008_auto_20180405_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
    ]
