# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_watch_api', '0010_station_station_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['id', 'sensor_data_dateTime', 'sensor__station_id', 'sensor__sensor_type_id'], 'verbose_name_plural': 'sensor data'},
        ),
    ]
