# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_watch_api', '0011_auto_20180504_0423'),
        ('water_watch_api', '0011_auto_20180502_2354'),
    ]

    operations = [
    ]
