from water_watch_api.views.home_page_view import HomePageView
from water_watch_api.views.station_map_view import StationMapView
from water_watch_api.views.dashboard_sensor_data_view import DashboardSensorDataView
from water_watch_api.views.sign_up_view import SignUpView
from water_watch_api.views.sign_in_view import SignInView


from water_watch_api.views.about_us_view import AboutUsView
from water_watch_api.views.contact_view import ContactView
from water_watch_api.views.project_detail_view import ProjectDetailView

from water_watch_api.views.sensor_data_view import SensorDataListCreateView
from water_watch_api.views.sensor_type_view import SensorTypeRetrieveUpdateDestroyView
from water_watch_api.views.sensor_type_view import SensorTypeListCreateView
from water_watch_api.views.sensor_data_view import SensorDataRetrieveUpdateDestroyView
from water_watch_api.views.sensor_maintenance_history_view import SensorMaintenanceHistoryRetrieveUpdateDestroyView
from water_watch_api.views.sensor_maintenance_history_view import SensorMaintenanceHistoryListCreateView


from water_watch_api.views.sensor_view import SensorRetrieveUpdateDestroyView
from water_watch_api.views.sensor_view import SensorListCreateView


from water_watch_api.views.station_view import StationRetrieveUpdateDestroyView
from water_watch_api.views.station_view import StationListCreateView

